[1,"\u001B[0m\u001B[1m\u001B[31merror\u001B[0m: Uncaught (in promise) Error: Project _quarto.yml validation failed.\n\nIn file _quarto.yml\n(line 6, columns 3--21) property name \u001B[34mtitle-block-banner\u001B[39m is invalid\n5: \u001B[34m  title: \"Data handling for biological sciences\"\u001B[39m\n6: \u001B[34m  title-block-banner: true\u001B[39m\n    ~~~~~~~~~~~~~~~~~~~\n7: \u001B[34m  # author: \"Edoardo Milanetti\"\u001B[39m\n\u001B[34mâ„¹\u001B[39m The error happened in location \u001B[34mbook\u001B[39m:\u001B[34mtitle-block-banner\u001B[39m.\n\n        throw new ValidationError2(errorMessage, yamlValidationErrors);\n\u001B[0m\u001B[31m              ^\u001B[0m\n    at \u001B[0m\u001B[1m\u001B[3mreadAndValidateYamlFromFile\u001B[0m (\u001B[0m\u001B[36mfile:///opt/quarto/bin/quarto.js\u001B[0m:\u001B[0m\u001B[33m20063\u001B[0m:\u001B[0m\u001B[33m15\u001B[0m)\n    at async \u001B[0m\u001B[36mfile:///opt/quarto/bin/quarto.js\u001B[0m:\u001B[0m\u001B[33m45521\u001B[0m:\u001B[0m\u001B[33m26\u001B[0m\n    at async \u001B[0m\u001B[1m\u001B[3mprojectContext\u001B[0m (\u001B[0m\u001B[36mfile:///opt/quarto/bin/quarto.js\u001B[0m:\u001B[0m\u001B[33m45376\u001B[0m:\u001B[0m\u001B[33m26\u001B[0m)\n    at async \u001B[0m\u001B[1m\u001B[3mrender\u001B[0m (\u001B[0m\u001B[36mfile:///opt/quarto/bin/quarto.js\u001B[0m:\u001B[0m\u001B[33m78999\u001B[0m:\u001B[0m\u001B[33m21\u001B[0m)\n"]
